name: Build and Push Resume

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install texlive texlive-latex-extra

    - name: build
      run: make

    - name: Save resume
      uses: actions/upload-artifact@v4
      with:
        name: sgreeneResume.pdf
        path: sgreeneResume.pdf

    - name: Upload resume to bucket
      uses: zdurham/s3-upload-github-action@master
      with:
        args: --endpoint-url=${{ secrets.AWS_S3_ENDPOINT }}
      env:
        FILE: ./sgreeneResume.pdf
        AWS_REGION: ${{ secrets.AWS_S3_REGION }}
        S3_BUCKET: ${{ secrets.AWS_S3_BUCKET }}
        S3_KEY: ${{ secrets.S3_KEY }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

