name: Build Resume

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: sudo apt install texlive texlive-latex-extra

    - name: build
      run: make

    - name: Save resume
      uses: actions/upload-artifact@v3
      with:
        name: sgreeneResume.pdf
        path: sgreeneResume.pdf

